line-length = 120

[lint]
# Default: E4, E7, E9, F
# E203: whitespace-before-punctuation (in preview for version 0.1.5)
# ISC: implicit-str-concat (in preview for version 0.1.5)
extend-select = ["C90", "Q", "W", "ISC", "E203", "COM"]
# I001: unsorted imports - fails when having multiline imports?
ignore = ["I001"]

[format]
quote-style = "single"

[lint.flake8-quotes]  # Q
inline-quotes = "single"

[lint.mccabe]  # C90
max-complexity = 10

[lint.pycodestyle]  # E,W
max-doc-length = 100
