# Generated by Django 5.0.3 on 2024-03-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                (
                    'name',
                    models.CharField(
                        help_text='The alias for the API key',
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('api_key', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_from', models.TimeField(help_text='Inclusive time - local tz')),
                ('interval_end', models.TimeField(help_text='Exclusive time - local tz')),
                ('unit_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('energy_type', models.CharField(choices=[('E', 'Electricity'), ('G', 'Gaz')], max_length=1)),
                ('metric_unit', models.CharField(choices=[('kWh', 'kWh'), ('m3', 'm3')], max_length=3)),
                ('direction', models.CharField(choices=[('I', 'Importing'), ('E', 'Exporting')], max_length=1)),
                ('valid_from', models.DateField(help_text='Inclusive date - at midnight')),
                ('valid_until', models.DateField(help_text='Exclusive date - at midnight')),
                ('currency', models.CharField(max_length=3)),
                ('default_rate', models.FloatField(help_text='Used when rates are not found', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPAN',
            fields=[
                (
                    'mpan',
                    models.CharField(
                        help_text='MPAN for electricity or MPRN for gas',
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('direction', models.CharField(choices=[('I', 'Importing'), ('E', 'Exporting')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'api_key',
                    models.ForeignKey(
                        default=None,
                        help_text='API Key - if absent no new requests to octopus are possible',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ingestion.apikey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('energy_type', models.CharField(choices=[('E', 'Electricity'), ('G', 'Gaz')], max_length=1)),
                ('metric_unit', models.CharField(choices=[('kWh', 'kWh'), ('m3', 'm3')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('mpan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.mpan')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField()),
                ('interval_start', models.DateTimeField(help_text='Interval start - inclusive')),
                ('interval_end', models.DateTimeField(help_text='Interval end - exclusive')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.meter')),
                (
                    'rate',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ingestion.rate',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tariff'),
        ),
        migrations.AddConstraint(
            model_name='consumption',
            constraint=models.UniqueConstraint(
                fields=('meter_id', 'interval_start', 'interval_end'),
                name='unique_consumption_interval',
            ),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(
                fields=('tariff_id', 'interval_from', 'interval_end'),
                name='unique_tariff_interval',
            ),
        ),
    ]
