# Generated by Django 5.0.3 on 2024-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='valid_from',
            field=models.DateField(help_text='Inclusive date - at midnight', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='valid_until',
            field=models.DateField(help_text='Exclusive date - at midnight', null=True),
        ),
    ]
