# Generated by Django 5.0.3 on 2024-04-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingestion', '0002_alter_tariff_valid_from_alter_tariff_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='tariff',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ingestion.tariff',
            ),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='valid_from',
            field=models.DateField(help_text='Inclusive date - at midnight'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Exclusive date - at midnight', null=True),
        ),
    ]
