on:
  pull_request:
  push:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install poetry
      shell: bash
      run: |
        pip install uv
        uv sync
    - name: Linting
      shell: bash
      run: |
        uv run ./scripts/lint.sh
